receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins:
            - http://localhost:3000
          allowed_headers:
            - "*"
          max_age: 7200

exporters:
  otlp:
    endpoint: jaeger:14250
    tls:
      insecure: true
  logging:
    verbosity: detailed

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, debug] 